# Generated by Django 4.2.6 on 2024-02-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleTitle', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='static')),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
