# Generated by Django 4.2.7 on 2024-01-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleTitle', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='text',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
