# Generated by Django 4.2.6 on 2024-02-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='introduction',
            field=models.TextField(default=int),
            preserve_default=False,
        ),
    ]
