# Generated by Django 4.2.7 on 2024-01-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_article_delete_text_delete_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to='static'),
            preserve_default=False,
        ),
    ]
